### ISSUE TITLE
Couple of unittests are failing

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#536] opened 2017-11-01 02:50 UTC
#### Issue Summary

```
======================================================================
ERROR: test_helloEmail (test.test_mail.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 88, in test_helloEmail
    mail = Mail()
  File "/home/travis/build/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py", line 45, in __init__
    self._validator = ValidateAPIKey()
NameError: name 'ValidateAPIKey' is not defined
======================================================================
ERROR: test_kitchenSink (test.test_mail.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 122, in test_kitchenSink
    mail = Mail()
  File "/home/travis/build/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py", line 45, in __init__
    self._validator = ValidateAPIKey()
NameError: name 'ValidateAPIKey' is not defined
======================================================================
ERROR: test_sendgridAPIKey (test.test_mail.UnitTests)
Tests if including SendGrid API will throw an Exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 45, in test_sendgridAPIKey
    mail = Mail()
  File "/home/travis/build/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py", line 45, in __init__
    self._validator = ValidateAPIKey()
NameError: name 'ValidateAPIKey' is not defined
======================================================================
ERROR: test_unicode_values_in_substitutions_helper (test.test_mail.UnitTests)
Test that the Substitutions helper accepts unicode values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 467, in test_unicode_values_in_substitutions_helper
    mail = Mail()
  File "/home/travis/build/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py", line 45, in __init__
    self._validator = ValidateAPIKey()
NameError: name 'ValidateAPIKey' is not defined
======================================================================
ERROR: test_hello_world (test.test_sendgrid.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_sendgrid.py", line 145, in test_hello_world
    content = Content("text/plain", "and easy to do anywhere, even with Python")
  File "/home/travis/build/sendgrid/sendgrid-python/sendgrid/helpers/mail/content.py", line 17, in __init__
    self._validator = ValidateAPIKey()
NameError: name 'ValidateAPIKey' is not defined
======================================================================
FAIL: test_asm_display_group_limit (test.test_mail.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 519, in test_asm_display_group_limit
    self.assertRaises(ValueError, ASM, 1, list(range(26)))
AssertionError: ValueError not raised by ASM
```

**Comment by party98** [comment] 2017-12-02 14:33
Hey I'd like to give it a try

**Comment by garuna-m6** [comment] 2017-12-08 18:41
is the issue still up ?

**Comment by thinkingserious** [comment] 2017-12-14 02:22
It looks like it's still available @garuna-m6, unless @party98 has started it and not made the PR just yet.

**Comment by garuna-m6** [comment] 2017-12-15 14:04
I think this one is solved already, tried to look up for the cause of these errors but lines don't exist anymore, running pytest is not giving same results.

**Comment by thinkingserious** [comment] 2017-12-15 21:21
Ah, thanks for the follow up @garuna-m6!

**Comment by party98** [comment] 2017-12-16 04:36
No, I have not started it yet. @garuna-m6 can take this up.

**Comment by garuna-m6** [comment] 2017-12-16 15:12
Any other issue still up? I think this one should be closed now.

**Comment by thinkingserious** [comment] 2017-12-19 01:25
You are correct, thanks @garuna-m6! Closing now.

**Closed by thinkingserious** 2017-12-19 01:25 UTC
Labels: hacktoberfest, help wanted, type: task, up for grabs
