### ISSUE TITLE
JSON quoted comma not ignored

### ISSUE THREAD

**Issue by codeFarmerJ** [sendgrid/sendgrid-python#578] opened 2018-05-30 23:52 UTC
#### Issue Summary

I'm using a python script to send emails. It mostly works.  Comma embedded in quotes are causing the submission to fail.

#### Steps to Reproduce

The input is a CSV file.

"Joe User",addr1@example.com,54321
"User, Joe",addr2@example.com,55555
The second line fails.

Python correctly parses the line and formats it as JSON, but it fails on submission. Apparently the quotes on name field are ignored and sees the embedded comma as a delimiter. It then uses User as the name and Joe as the email address and fails.

Is this a known bug? Is there a work-around?

#### Technical details:

* sendgrid-python 5.3.0
* Python Version: 2.7.3

**Comment by shubhambhattar** [comment] 2018-10-06 21:55
I would like to try to solve this. Any idea where should I start (which files should I focus on)?

**Comment by cmccandless** [comment] 2018-10-06 22:18
This was raised in #618

**Comment by shubhambhattar** [comment] 2018-10-07 08:40
@cmccandless So the issue is resolved?

**Comment by cmccandless** [comment] 2018-10-08 12:28
@shubhambhattar yes, that is what I intended to say. Apologies for the typo.

**Comment by cmccandless** [comment] 2018-10-08 12:30
Note: it was requested that #618 be targeted at the v4 branch instead of the master branch, so the issue keywords did not close this issue. It is probable that when v4 is merged with master, this issue will automatically be closed.

**Comment by shubhambhattar** [comment] 2018-10-08 18:55
@cmccandless Okay. Thanks for the clarification.

**Comment by cmccandless** [comment] 2018-10-09 18:33
Also, possible duplicate of #291

**Comment by medmunds** [comment] 2019-08-21 21:48
Yes, this is the same underlying "commas in recipient display names" API problem as #291, and is not actually related to CSV files or JSON. More info and outline for a fix is in [this comment](https://github.com/sendgrid/sendgrid-python/issues/291#issuecomment-340097963).

Just a heads up that the code merged in #618 likely injects a couple of new issues:

* It adds unnecessary quotes around display names in the *From* and *Reply-To* headers, which will be displayed to recipients in most email clients. (So *From: Widgets, Inc.* will show up as *From: "Widgets, Inc."* in Gmail after the fix.) This is probably minor, but it's a change from current behavior. And I suppose there's a chance these look like [scare quotes](https://en.wikipedia.org/wiki/Scare_quotes) when users see them alongside other messages that don't wrap the sender name in extra quotes.

* It calls [`html.unescape`](https://docs.python.org/3/library/html.html#html.unescape) on all email display names. I'm not sure what this was meant to do—HTML entities are not relevant to email headers. It's *probably* harmless for most real-world names, but could cause unexpected behavior for certain names containing `&` and `;`. (Maybe the intent was something like [`email.utils.quote`](https://docs.python.org/3/library/email.util.html#email.utils.quote)?)

**Comment by thinkingserious** [comment] 2021-03-11 02:21
Since there has been no activity on this issue since March 1, 2020, we are closing this issue. Please feel free to reopen or create a new issue if you still require assistance. Thank you!

**Closed by thinkingserious** 2021-03-11 02:21 UTC
Labels: difficulty: medium, status: work in progress, type: community enhancement
