### ISSUE TITLE
Responses with HTTP 406 status codes with NGINX HTML responses

### ISSUE THREAD

**Issue by nickdirienzo** [sendgrid/sendgrid-python#154] opened 2015-11-30 22:49 UTC
Hey there!

We're experiencing a really strange issue with requests to `https://api.sendgrid.com:443/api/mail.send.json`: we're seeing some responses with HTTP 406 status codes and NGINX's standard error page. 

I've tried sending requests to that endpoint with this API client and using `urllib` (well, `urlfetch` on Google App Engine). However, we're seeing pretty much the same issue as what's described here: https://github.com/sendgrid/sendgrid-csharp/issues/126

Sorry if this isn't the right place for this, but I think it's worth bringing up. Let me know if I can provide more information.

Thanks,
Nick

**Comment by mbernier** [comment] 2015-11-30 22:52
Thank you for letting us know! 

We are actively looking into this issue and will let you know what we find out as soon as we have a solution.

**Comment by nickdirienzo** [comment] 2015-11-30 22:52
Thanks @mbernier!

**Comment by mbernier** [comment] 2015-11-30 23:04
Hey @nickdirienzo could i ask you to please send in a support ticket? support@sendgrid.com so that we can ask you a couple questions?

**Comment by nickdirienzo** [comment] 2015-11-30 23:05
Already have a ticket open (550040). My email should be attached to it... if not, let me know!

**Comment by mbernier** [comment] 2015-11-30 23:06
Perfect, I will close this issue and we will chat that way. Thank you so much!

**Closed by mbernier** 2015-11-30 23:06 UTC

**Comment by gsakkis** [comment] 2015-12-01 14:43
FYI that's a duplicate of #149

**Comment by nickdirienzo** [comment] 2015-12-01 16:30
Oops. Should've searched. Thanks for noting @gsakkis.
