### ISSUE TITLE
Fix "similar-code" issue in sendgrid/helpers/mail/personalization.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#502] opened 2017-10-30 05:49 UTC
Similar blocks of code found in 6 locations. Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/personalization.py#issue_59f639d0343eae0001000086

**Comment by codervikash** [comment] 2017-10-30 09:44
duplicate of #501

**Closed** 2018-02-27 21:41 UTC
Labels: hacktoberfest
