### ISSUE TITLE
401 Unauthorized exception never caught

### ISSUE THREAD

**Issue by bc-ben** [sendgrid/sendgrid-python#966] opened 2021-01-13 18:40 UTC
### Issue Summary
In a situation where a "401 - Unauthorized" exception should be caught, it is superceded by urllib's "IncompleteRead" exception. Therefore, it is not possible to catch a 401 Unauthorized Exception.

### Code Snippet
```python
import sendgrid
from python_http_client import exceptions

message = Mail(
    from_email=foo@bar.com,
    to_emails=bar@foo.com,
    subject="A Subject",
    html_content="Some content")

sg = sendgrid.SendGridAPIClient(api_key="IncorrectAPIKey")
try:
    r = sg.send(message)
except exceptions.UnauthorizedError:
    print("Unauthorized!")
except Exception:
    print("Some other exception")
```

### Exception/Log
The console will always print out `Some other exception` because the IncompleteRead exception overtakes the original 401 - Unauthorized exception.

Example detailed exception logs can be seen in issue and #576 and #835 but is also here:

```
Traceback (most recent call last):
File "/home/akshay/.local/lib/python3.6/site-packages/python_http_client/client.py", line 172, in _make_request
return opener.open(request, timeout=timeout)
File "/usr/lib/python3.6/urllib/request.py", line 532, in open
response = meth(req, response)
File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.6/urllib/request.py", line 570, in error
return self._call_chain(*args)
File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./apicall.py", line 46, in 
response = sg.send(message)
File "/home/akshay/.local/lib/python3.6/site-packages/sendgrid/sendgrid.py", line 98, in send
response = self.client.mail.send.post(request_body=message.get())
File "/home/akshay/.local/lib/python3.6/site-packages/python_http_client/client.py", line 252, in http_request
return Response(self._make_request(opener, request, timeout=timeout))
File "/home/akshay/.local/lib/python3.6/site-packages/python_http_client/client.py", line 174, in _make_request
exc = handle_error(err)
File "/home/akshay/.local/lib/python3.6/site-packages/python_http_client/exceptions.py", line 82, in handle_error
exc = err_dicterror.code
File "/home/akshay/.local/lib/python3.6/site-packages/python_http_client/exceptions.py", line 10, in init
self.body = error.read()
File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
return func(*args, **kwargs)
File "/usr/lib/python3.6/http/client.py", line 462, in read
s = self._safe_read(self.length)
File "/usr/lib/python3.6/http/client.py", line 614, in _safe_read
raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 116 more expected)
```

### Technical details:
The issue seems to be line 10 of `python_http_client/exceptions.py`. It is unable to complete the `error.read()` function and then raises its own IncompleteRead exception (from urllib3) because the function has a mismatch of data expectations.

I'm not sure if this also occurs with other SendGrid exceptions because I'm not sure how to trigger those as easily as "Unauthorized".

* sendgrid-python version: 6.4.8
* python version: 3.8

**Comment by thinkingserious** [comment] 2021-01-13 19:43
Hello @bc-ben,

Thank you for raising this issue!

I am unable to reproduce this. Here is the code that I used:

```python
import sendgrid
from sendgrid.helpers.mail import *
from python_http_client import exceptions

message = Mail(
    from_email="foo@bar.com",
    to_emails="bar@foo.com",
    subject="A Subject",
    html_content="Some content")

sg = sendgrid.SendGridAPIClient(api_key="IncorrectAPIKey")
try:
    r = sg.send(message)
except exceptions.UnauthorizedError:
    print("Unauthorized!")
except Exception:
    print("Some other exception")
```
and the response was:
```bash
Unauthorized!
```
Could you please take a look and let me know what you think?

I tested on Python 3.8.3 with `sendgrid-python` 6.4.8 and `python-http-client` 3.3.1.

Thanks!

With best regards,

Elmer

**Comment by shwetha-manvinkurke** [comment] 2021-02-18 00:23
@bc-ben Closing this issue. Please feel free to reopen if you need further help

**Closed by shwetha-manvinkurke** 2021-02-18 00:23 UTC
Labels: status: waiting for feedback, type: question
