### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by rashgang** [sendgrid/sendgrid-python#841] opened 2019-09-16 11:21 UTC
#### Issue Summary

Hello, I'm sorry when I log in my account it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.

#### Steps to Reproduce

My email is a rashgang83@gmail.com 
After I sign up, it auto login successfully.
Then I log out and re-login, it will appear the case
![Screenshot from 2019-09-16 16-50-32](https://user-images.githubusercontent.com/4287244/64954070-23e4a780-d8a2-11e9-92fb-14459d92c043.png)

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

I have contacted support team. i didnt get response

**Comment by skliarovartem** [comment] 2019-10-22 11:03
use sendinblue, much better

**Comment by XIAOXIAOSIYU** [comment] 2019-11-06 01:26
@skliarovartem Since they will never fix it or even explain it to users, I'm gonna say I agree with you.

**Comment by Stephen195** [comment] 2019-11-21 15:40
I got the same issue

**Comment by TorvaldsDB** [comment] 2019-11-28 06:10
Same issue. I am almost crazy.

**Comment by dan-ward** [comment] 2019-12-05 21:57
same issue, on the paid account and unable to send emails.  Anyone gotten a response from support yet?  Submitted my ticket this morning and no response.

**Comment by sebsronnie** [comment] 2020-01-02 07:26
How long does it take Sendgrid to respond to their customers? I'm facing the same issue and I'm about to run crazy at the the lack of support.

**Comment by eshanholtz** [comment] 2020-01-22 18:45
Hello @rashgang 

Since this is not an issue with the helper library itself, I'm going to tag this as needing support, which will auto-close the issue on Github. I also recognize that support has been slow to respond to this issue, so I will be pinging them directly to follow up.

Thank you for your patience,
Elise

**Comment by thinkingserious** [comment] 2020-01-22 18:45
Hello @rashgang,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Closed by thinkingserious** 2020-01-22 18:45 UTC
Labels: difficulty: unknown or n/a, status: help wanted, type: non-library issue, type: support

**Comment by eshanholtz** [comment] 2020-01-22 19:42
After talking to support, it appears these issues are caused by account being deactivated automatically from hitting some account vetting traps put in place by our Compliance team. When this happens, we ask our customers do the following:
1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
2. Click on Trouble Logging In
3. Click "I am having a different log in issue"

To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

Hope this helps,
Elise

**Comment by iddify** [comment] 2020-02-07 10:46
I had the same issue, contacted the support, been almost 5 days with no answer, i'm moving to `sendinblue`. thanks for the suggestion @skliarovartem

**Comment by neetukanaujia** [comment] 2020-02-27 11:46
same issue

**Comment by ravindra98** [comment] 2020-05-03 17:29
I am having the same issue. It says that I am not authorized to login. All I did in the past with sendgrid is that I created a Account. Thats it. And from last some days I am getting some delivery failed mails from sengrid account whose owners mail address is same as mine. PLease assist.

**Comment by childish-sambino** [comment] 2020-05-04 15:10
@ravindra98 Are you saying there are some failure deliveries _and_ you're unable to sign in? Either way, this is not something that can be solved in this library so best to contact support as detailed above.

**Comment by djsoul86** [comment] 2020-05-06 15:27
I got the same issue, and i haven´t receive any response.

**Comment by childish-sambino** [comment] 2020-05-06 15:44
@djsoul86 Did you follow the steps listed here: https://github.com/sendgrid/sendgrid-python/issues/841#issuecomment-577352769

**Comment by djsoul86** [comment] 2020-05-06 15:54
@childish-sambino yes! and i recieve a mail with the following message : 

Thanks for contacting Twilio SendGrid's Support team!

We've received your request, and we're diligently working 24/7 to address your issue. We will certainly help you out as soon as we can.

To check the status of the ticket and add additional comments, follow the link here.... 

But, not even can logging in, then how i can see the ticket. :(

**Comment by djsoul86** [comment] 2020-05-08 18:32
Why nobody attend the tickets??? I feel that lost my money.

**Comment by childish-sambino** [comment] 2020-05-08 18:34
@djsoul86 I've reached out to support but don't have a timetable yet.

**Comment by djsoul86** [comment] 2020-05-11 14:04
The worst service ever, not recommended, simply i lost my money of two accounts.

**Comment by adamchasetaylor** [comment] 2020-05-11 16:20
@iddify , @ravindra98 , @neetukanaujia , @djsoul86 - 

It sounds like your account status might be under review. You should have received [a notice](https://sendgrid.com/docs/ui/account-and-settings/account-under-review/) in your e-mail with more details.

If you would like to discuss it, please respond to the email you received regarding the notice. 

If you cannot find this e-mail, we ask our customers do the following:

> 
> 1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
> 2. Click on Trouble Logging In
> 3. Click "I am having a different log in issue"
> 
> To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

Support cannot assist in reactivation of banned accounts.

Hope this helps!
Twilio SendGrid Team

**Comment by djsoul86** [comment] 2020-05-11 16:47
@adamchasetaylor  I used my account to send mails, then the dashboard warning me that my account was under review, i dont know why but the next day the login wasn't work anymore, i never received a mail indicating the reason. I think sendgrid should say the reason before block completely an account because i payed 30 dollars by a services that i only can used once. Support never attended my tickets, nobody says anything, i lost my money. Really bad customer service.

**Comment by adamchasetaylor** [comment] 2020-05-11 18:02
@djsoul86 - Please respond to the email you received regarding the notice and and one of our fantastic support people will get back to you.

**Comment by adamchasetaylor** [comment] 2020-05-11 18:04
@djsoul86 - If you cannot find this e-mail, we ask our customers do the following:

> If you cannot find this e-mail, we ask our customers do the following:
> 
> > 1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
> > 2. Click on Trouble Logging In
> > 3. Click "I am having a different log in issue"
> > 
> > To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.
> 
> Support cannot assist in reactivation of banned accounts.
